const ITEMS_FETCHING = 'ITEMS_FETCHING',
  ITEMS_FETCHED = 'ITEMS_FETCHED',
  ACTIVE_ITEM_UPDATED = 'ACTIVE_ITEM_UPDATED',
  CHANGE_COUNTRY = 'CHANGE_COUNTRY',
  CHANGE_DISEASE = 'CHANGE_DISEASE',
  CLEAR_ACTIVE = 'CLEAR_ACTIVE',
  CLEAR_COUNTRY = 'CLEAR_COUNTRY',
  CLEAR_DISEASE = 'CLEAR_DISEASE',
  FAILED_FETCH = 'FAILED_FETCH',

  CLEAR_ = {
    ACTIVE: CLEAR_ACTIVE,
    DISEASE: CLEAR_DISEASE,
    COUNTRY: CLEAR_COUNTRY
  }

export {
  ITEMS_FETCHING,
  ITEMS_FETCHED,
  ACTIVE_ITEM_UPDATED,
  FAILED_FETCH,
  CLEAR_ACTIVE,
  CHANGE_COUNTRY,
  CHANGE_DISEASE,
  CLEAR_COUNTRY,
  CLEAR_DISEASE,
  CLEAR_
};
